
from django import forms
from django.contrib.auth.models import User
from .models import Perfil
from django.core.exceptions import ValidationError

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class EditPerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['avatar', 'bio', 'fecha_nacimiento']

class RegistroForm(forms.ModelForm):
    password1 = forms.CharField(label='Contrase침a', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmar contrase침a', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("Este nombre de usuario ya est치 en uso.")
        return username

    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get("password1")
        p2 = cleaned_data.get("password2")
        if p1 and p2 and p1 != p2:
            raise ValidationError("Las contrase침as no coinciden.")